name: Terraform tests

permissions:
  contents: read # This is required for actions/checkout
  id-token: write # This is required for requesting the JWT
  pull-requests: write # This is required for actions/github-script

on:
  pull_request:
    branches:
      - main

env:
  RUN_NUMBER: ${{ github.run_number }}
  TERRAFORM_DOCS_VERSION: v0.16.0
  TFLINT_VERSION: v0.46.1

jobs:
  pre-commit:
    name: Pre commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Find terraform version
        id: maxVer
        uses: clowdhaus/terraform-min-max@v1.2.4

      - id: private-modules
        uses: philips-labs/terraform-private-modules-action@v1
        with:
          org: dinocloud
          token: ${{ secrets.DOWNLOAD_PRIVATE_REPOSITORIES }}

      - name: Pre-commit Terraform ${{ steps.maxVer.outputs.maxVersion }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.8.3
        with:
          terraform-version: ${{ steps.maxVer.outputs.maxVersion }}
          tflint-version: ${{ env.TFLINT_VERSION }}
          terraform-docs-version: ${{ env.TERRAFORM_DOCS_VERSION }}
          install-hcledit: true

  security-scan:
    name: Security checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Run kics Scan
        uses: checkmarx/kics-github-action@v1.7.0
        with:
          path: '.'
          ignore_on_exit: results
          output_path: kicsScan/
